# NOTE: docker-compose will create network automatically
# this allows the containers to communicate with each other
version: '3.4'

services:
  twitter-search:
    image: nathanesau/twitter-clone:twitter-search
    container_name: twitter-search
    restart: always
    environment:
      - node.name=twitter-search
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: host
  twitter-app:
    image: nathanesau/twitter-clone:twitter-app
    container_name: twitter-app
    restart: always
    volumes:
      - data02:/data
    ports:
      - 5000:5000
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/app.db
      - ELASTICSEARCH_URL=http://127.0.0.1:9200/
    depends_on:
      - twitter-search
  pastebin-app:
    image: nathanesau/pastebin-clone:pastebin-app
    container_name: pastebin-app
    restart: always
    volumes:
      - data03:/data
    ports:
      - 5001:5001
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/app.db
  pastebin-bgtasks:
    image: nathanesau/pastebin-clone:pastebin-bgtasks
    container_name: pastebin-bgtasks
    restart: always
    network_mode: host
    environment:
      - PASTEBIN_API_URL=http://127.0.0.1:5001/pastebin-clone/api
    depends_on:
      - pastebin-app
  site-nginx:
    build: site-nginx
    image: nathanesau/site-clones:site-nginx
    container_name: site-nginx
    restart: always
    ports:
      - 80:80
    network_mode: host
    depends_on: 
      - twitter-app
      - pastebin-app
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local